### ISSUE TITLE
NPM does not allow ads to be displayed on installation

### ISSUE THREAD

**Issue by kpfefferle** [shipshapecode/ember-assign-polyfill#64]
When running `yarn install` in a project using this polyfill, the console outputs the following advertisement:

![ad](https://user-images.githubusercontent.com/250934/93811169-bb9b7500-fc1d-11ea-8f51-978d934a1ecd.png)

NPM's policies prohibit the display of advertisements by packages during installation. From NPM's [Open Source Policies](https://github.com/npm/policies/blob/6097a653a5de1baadf771ecf41ef1354a70c4f5a/open-source-terms.md#commercial-content):

> These kinds of commercial content generally aren't acceptable:
> ...
> 2. Packages that display ads at runtime, on installation, or at other stages of the software development lifecycle, such as via npm scripts.

NPM's CTO made some additional comments regarding this issue about a year ago when this policy was put into place: https://www.zdnet.com/article/npm-bans-terminal-ads/

It looks like [the offending code](https://github.com/shipshapecode/ember-assign-polyfill/blob/b91b9aa8f43b747c651f450b5f7e57eff588b368/index.js#L16) was added 2 months ago by #60, I assume unaware that this behavior had already been banned by NPM?

**Comment by RobbieTheWagner** [comment]
@kpfefferle I was unaware this was banned. There seem to be many projects logging whatever they want, like core-js asking for a job for the maintainer etc. Are you positive this isn't okay? We maintain the package, and I don't think mentioning we can help if you want is that bad.

**Comment by kpfefferle** [comment]
@rwwagner90 I assumed that you were not aware of the policy since the ad was just recently added, but it's definitely not okay to be doing this. We've had multiple developers at our company specifically complain about your ad, leaving them with a bad impression of Ship Shape - which is why I'm trying to bring it to your attention and get it fixed rather than file a complaint with NPM or some other escalating nonsense.

As for core-js, you can see the backlash against that project's behavior in https://github.com/zloirock/core-js/issues/635. The core-js package has even seen [forks specifically geared around removing the ad](https://www.npmjs.com/package/core-js-without-ads).

My assumption is you're not seeing a wider backlash (yet) since the number of projects that are both on an older version of Ember and also using forward-facing polyfills such as this one are few. The Ember community has long had a reputation for its spirit of community and collaboration, so I'm hoping that you will do the right thing and remove this advertisement without the need for this project to be forked and/or reported to NPM.

**Comment by RobbieTheWagner** [comment]
@kpfefferle To me, it seems like NPM is the bad guy here. People providing countless hours of their free time for open source, free software, who just want to put a small message in the console advertising to help them sustain their efforts should not be banned for doing so.

I'll merge your PR and comply, but I do not understand why you or your colleagues are upset by the message. If you were interested in help updating, you might be glad to see the message. There are always two sides to see and empathize with.

**Comment by kpfefferle** [comment]
@rwwagner90 Thank you in advance for merging the PR to remove the ad.

NPM's policy was written in direct response to widespread and vocal backlash throughout the community against the particular practice of advertising in the console. Our company in particular has engineers already dedicated to upgrading our version of Ember, and having an advertisement appear every time any developer in the company runs `yarn install` in our Ember project feels spammy *really* fast and thus reflects negatively on Ship Shape.

Most of the Ember-focused devs in our company have spent considerable time working as consultants and involved in open source, so we certainly sympathize with the challenge of finding support to sustain those efforts. Please know that we wish you and Ship Shape well, and we fully support the other solicitation efforts you've made via this project's README and "Sponsor" button. A huge part of my motivation in bringing this to you directly has been the hope of addressing the issue without doing further damage to Ship Shape's reputation. I assure you that I have no interest in dragging you, Ship Shape, or anyone else in the Ember community through the mud.
