### ISSUE TITLE
SyntaxError: Expected an identifier but found '.' instead

### ISSUE THREAD

**Issue by Panman82** [shipshapecode/ember-assign-polyfill#7]
I tried [updating to 2.0.0 in another addon](https://github.com/froala/ember-froala-editor/commit/5e5948e8841cd92d6c95c0be8ba769de7a78b1b7) but got a [Travis CI error](https://travis-ci.org/froala/ember-froala-editor/jobs/201217159#L507) for the ember-lts-2.4 scenario. [Reverting](https://github.com/froala/ember-froala-editor/commit/afe0c78a31ba40054776396d1132f0dd06507281) back to 1.0.0 [resolves the issue](https://travis-ci.org/froala/ember-froala-editor/builds/201232627). Not sure what's going on here, new to Travis CI so I'm not sure how to see what `vendor.js:66484` is..

> SyntaxError: Expected an identifier but found '.' instead

**Comment by RobbieTheWagner** [comment]
@Panman8201 this is now a true polyfill, meaning `Ember.assign` itself is polyfilled. You'll need to either use `Ember.assign` directly or destructure it out.

```js
import Ember from 'ember';
const { assign } = Ember;
```

**Comment by Panman82** [comment]
@rwwagner90 Yep, I had done that: https://github.com/froala/ember-froala-editor/commit/5e5948e8841cd92d6c95c0be8ba769de7a78b1b7#diff-9b72a3cabe276e9f8eb2515ef5669604L121

**Comment by RobbieTheWagner** [comment]
@Panman8201 hmm, it works for me in my apps. Unsure why it would make a difference, but maybe try destructuring? Also, are you sure you have the latest version installed? You removed node_modules and reinstalled and all that to be sure?

**Comment by Panman82** [comment]
Huh, I'm at a loss as well. Works fine on ember-twiddle, but fails when running an ember-try test for ember-lts-2.4 (both locally and on Travis CI).

> You removed node_modules and reinstalled and all that to be sure?

While I could `nombom`, it wouldn't really effect test scenarios because deps are re-downloaded.

> maybe try destructuring?

I'll give that a try, but not sure why that would work if it did.

**Comment by Panman82** [comment]
I was able to dissect that file locally, here is what that line number is referring to;

```
  if (!_Ember.assign) {
    _Ember.assign = function(...objects) { // << Error on this line
      return objects.reduce(Ember.merge);
    };
  }
```

My guess is that it doesn't like the spread operator. I'm on node v4 BTW, local tests run in Phantom.

**Comment by rwjblue** [comment]
https://github.com/shipshapecode/ember-assign-polyfill/pull/8 should fix

**Comment by RobbieTheWagner** [comment]
@Panman8201 2.0.1 released, please try it out!

**Comment by Panman82** [comment]
Bingo, works! Thanks everyone, Rob just seems to magically appear sometimes. 😄 

https://travis-ci.org/froala/ember-froala-editor/builds/201533633
